name: ArxivSummary
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - arxiv
    - requests
    - PyPDF2
    - llama-index
    - openai
    - torch
    - transformers