name: ArxivSummary
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - arxiv
    - requests
    - PyPDF2
    - llama-index
    - python-dotenv
    - llama-index-llms-azure-openai
    - llama-index-embeddings-azure-openai
    - pandas
    - markdown2
    - azure-keyvault
    - pyarrow
    - matplotlib
    - seaborn
    - spacy
    - sentence_transformers
    - plotly