name: summary
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - arxiv==2.1.3
    - requests==2.32.3
    - llama-index
    - python-dotenv==1.0.1
    - llama-index-llms-azure-openai
    - llama-index-embeddings-azure-openai
    - pandas==2.2.3
    - azure-keyvault-secrets
    - azure-identity
    - markdown2